#GLOBAL FILES
OBJS = main.cpp

CC = g++

#EMPTY SYMBOL
EMPTY =

#RESOURCE PATHS
INCLUDE_PATHS = -I.\include
LIBRARY_PATHS = -L.\lib

RESOURCE_PATHS = $(INCLUDE_PATHS) $(LIBRARY_PATHS)

#COMPILER FLAGS
LINKER_FLAGS = $(EMPTY)

RELEASE_FLAGS = -w -Wl,-subsystem,windows $(LINKER_FLAGS)
DEBUG_FLAGS = $(EMPTY) $(LINKER_FLAGS)

#EXECUTABLE NAMES
OBJ_NAME = UNTITLED
DBG_NAME = ${OBJ_NAME:=_debug}

#COMPILE OPTIONS
all : release debug
	
release : $(OBJS)
	$(CC) $(OBJS) $(RESOURCE_PATHS) $(RELEASE_FLAGS) -o $(OBJ_NAME)
	
debug : $(OBJS)
	$(CC) $(OBJS) $(RESOURCE_PATHS) $(DEBUG_FLAGS) -o $(DBG_NAME)